package:
    name: ci-psi4
    version: 1.2

build:
    number: 0

requirements:
    run:
        - python {{ python }}
        - psi4

about:
    summary: 'a continuous integration offset download counter for Psi4'
    description: >
      We'd like to know which of our downloads are users and which are
      continuous integration bots. This is just a metapackage to track
      the latter, so use it in your `travis.yml` and the like. I regret
      that due to forces beyond my understanding, you have to specify
      psi4 as well to get sensible version behavior for py27, so use the
      following for stable release (e.g., v1.1 or v1.2) and nightly
      build respectively.

        conda create -q -n p4env python=x.x ci-psi4 psi4 -c psi4

        conda create -q -n p4env python=x.x ci-psi4 psi4 -c psi4/label/dev

