{% set version = "1.0" %}

package:
    name: sphinx-psi-theme
    version: {{ version }}

source:
    git_url: git@github.com:psi4/sphinx-psi-theme.git      # [linux]
    git_url: https://github.com/psi4/sphinx-psi-theme.git  # [osx]
    git_tag: v{{ version }}

build:
    skip: true           # [win]
    number: 0            # [osx]
    number: 0            # [linux]
    preserve_egg_dir: True
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python {{ python }}
        - setuptools
    run:
        - cloud_sptheme
        - docutils 0.12*
        - {{ pin_compatible('python', max_pin='x.x') }}
        - sphinx >=1.5

test:
    imports:
        - sphinx_psi_theme
        - sphinx_psi_theme.ext

about:
    home: https://github.com/psi4/sphinx-psi-theme
    dev_url: https://github.com/psi4/sphinx-psi-theme
    # doc_url:
    # doc_source_url:
    license: BSD-3-Clause
    license_url: https://opensource.org/licenses/BSD-3-Clause
    license_file: LICENSE
    license_family: BSD
    summary: "theme for Psi4 Sphinx docs, derived from Cloud"
    # description: >
