{% set version = "0.9" %}

package:
    name: v2rdm_casscf
    version: {{ version }}

source:
    git_url: git@github.com:loriab/v2rdm_casscf.git      # [linux]
    git_url: https://github.com/loriab/v2rdm_casscf.git  # [osx]
    # git_tag: v{{ version }}
    # git_tag: ae46114                                     # L4,M2: l2 for v2rdm4
    # git_tag: f3dbac4                                     # L6,M3: lagrangian
    # git_tag: 7a4204c                                     # L7,M4: new cmake
    git_tag: 929d7fc                                     # L9: mkl2021  L8M5: sobasis_
    #path: ../../../v2rdm_casscf

build:
    number: 9                                            # [linux]
    number: 6                                            # [osx]
    binary_relocation: true
    skip: true                                           # [win]
    ignore_run_exports:
        # interferes with solving build env (at least for prereleases?)
        - psi4
        # unused libraries
        - libgfortran-ng
        - mpfr
        - eigen

requirements:
    build:
        - cmake >=3.15
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - llvm-openmp                                    # [osx]
    host:
        - eigen
        - mkl-devel {{ mkl }}
        - mpfr
        - psi4 {{ psi4ver }}                              # for psi4OptionsTools to initiate plugin and to link against
        - pybind11-headers {{ pybind11 }}
        - python {{ python }}                             # to resolve site-packages dir name
    run:
        - intel-openmp
        - {{ pin_compatible('python', max_pin='x.x') }}

test:
    requires:
        - psi4 {{ psi4ver }}
    imports:
        - v2rdm_casscf
        - psi4
    commands:
        # Verify module
        - test -f $SP_DIR/v2rdm_casscf/v2rdm_casscf.so
        - test -f $PREFIX/share/cmake/v2rdm_casscf/v2rdm_casscfConfig.cmake
        # Inspect linkage
#        - ldd -r -u $SP_DIR/v2rdm_casscf/v2rdm_casscf.so && return 0  # [linux]
        - ldd -v $SP_DIR/v2rdm_casscf/v2rdm_casscf.so                 # [linux]
        - otool -L $SP_DIR/v2rdm_casscf/v2rdm_casscf.so               # [osx]
        - conda inspect linkages --show-files --groupby=dependency v2rdm_casscf
        - conda inspect objects -p $PREFIX $PKG_NAME                  # [osx]
        # Actually test
        - psi4 --test
        # * conda-build and pytest-shutil don't get along
        - python -c "import v2rdm_casscf as v2, sys; sys.exit(v2.test('long', extras=['-k', 'psiapi']))"
        - python -c "import v2rdm_casscf as v2; import psi4; print('*** v2rdm_casscf {} built successfully against Psi4 {}. Buy psinet a beer.'.format(v2.__version__, psi4.__version__))"

about:
    home: https://github.com/edeprince3/v2rdm_casscf
    dev_url: https://github.com/edeprince3/v2rdm_casscf
    doc_url: https://github.com/edeprince3/v2rdm_casscf/blob/master/README.md
    # doc_source_url:
    license: GPL-2.0+
    license_url: https://opensource.org/licenses/GPL-2.0+
    license_file: LICENSE
    license_family: GPL
    summary: "E. DePrince's variational 2-RDM-driven CASSCF plugin to Psi4"
    # description: >

# NOTES
# -----

# * leave mainline
#    git_url: git@github.com:edeprince3/v2rdm_casscf.git      # [linux]
#    git_url: https://github.com/edeprince3/v2rdm_casscf.git  # [osx]
#    git_tag: d799503                                     # M0,L3,L4: P::e L2: pb11 250 L1: mkl2019/2020, L0: v2rdm8 = v0.9 + 6 (edp) + 2 (lab)

# * To build against a certain, non-latest psi4, `req/host` will be e.g., `psi4 1.1+add49b9`

# * v0.8 era
#    git_tag: e155289         # L5,6,7,8,9,10,11,M5,6,7,8,9,10: e155289 = v0.8 + 26 (no L4)
#                             # L3: loriab-patch-1 v0.8 + ~7 (codata2014 fix)
#                             # L1,2: 976d8af = v0.8 + 1 (version bump)
#    number: 11                                           # [linux]
#    number: 10                                           # [osx]
