echo ""
echo "  Thank you for installing Psi4."
echo "    Website: psicode.org"
echo "    Forum:   forum.psicode.org"
echo "    Manual:  psicode.org/psi4manual/master/index.html"
echo "    GitHub:  github.com/psi4/psi4"
echo "    Binary:  anaconda.org/psi4/psi4"
echo "    Inputs:  /opt/anaconda1anaconda2anaconda3/share/psi4/samples"
#echo "    Youtube: youtube.com/user/psitutorials"
echo "    Test (after first activating conda installation or environment):"
#echo "      psi4 \"\$(dirname \$(which psi4))\"/../share/psi4/samples/sapt1/test.in"
echo "      psi4 /opt/anaconda1anaconda2anaconda3/share/psi4/samples/sapt1/test.in"
echo "      psi4 --test"
echo ""
echo "  For csh/tcsh command-line use, add to shell or ~/.tcshrc file:"
#echo "    unsetenv PSIDATADIR"
#echo "    setenv PATH /opt/anaconda1anaconda2anaconda3/bin:\$PATH"
echo "    source /opt/anaconda1anaconda2anaconda3/etc/profile.d/conda.csh"
echo "    conda activate"
echo "    setenv PSI_SCRATCH /path/to/existing/writable/local-not-network/disk/for/scratch/files"
echo ""
if [ "$(uname)" == "Darwin" ]; then
echo "  For sh/bash command-line use, add to shell or ~/.bash_profile file:"
elif [ "$(uname)" == "Linux" ]; then
echo "  For sh/bash command-line use, add to shell or ~/.bashrc file:"
fi
#echo "    unset PSIDATADIR"
#echo "    export PATH=/opt/anaconda1anaconda2anaconda3/bin:\$PATH"
echo "    source /opt/anaconda1anaconda2anaconda3/etc/profile.d/conda.sh"
echo "    conda activate"
echo "    export PSI_SCRATCH=/path/to/existing/writable/local-not-network/disk/for/scratch/files"
echo ""
#echo "  Report problems at http://forum.psicode.org/t/report-conda-update-psi4-oddities-here/32"
