{% set name = "resp" %}
{% set version = "0.8.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_url: git@github.com:cdsgroup/resp.git
    git_tag: v{{ version }}
    # git_tag: master

build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
    host:
        - python >=3.6
        - pip
    run:
        - numpy
        - python >=3.6

test:
    requires:
        - psi4
    imports:
        - psi4
        - resp
    commands:
        # Verify module
        - test -f $SP_DIR/resp/driver.py
        # Inspect linkage
        - conda inspect linkages --show-files --groupby=dependency resp
        # Actually test
        - psi4 --test
        - python -c "import resp, sys; sys.exit(resp.test())"
        - python -c "import psi4, resp; print('*** resp {} built successfully against Psi4 {}. Buy psinet a beer.'.format(resp.__version__, psi4.__version__))"

about:
    home: https://github.com/cdsgroup/resp
    dev_url: https://github.com/cdsgroup/resp
    # doc_url:
    # doc_source_url:
    license: BSD-3-Clause
    license_url: https://opensource.org/licenses/BSD-3-Clause
    license_file: LICENSE
    license_family: BSD
    summary: "A. Alenaizan's restrained electrostatic potential (RESP) plugin to Psi4"
    # description: >
