{% set version = "2.6.0" %}

package:
    name: libint2
    version: {{ version }}

source:
    url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export30-5-4-3.tgz
    #git_url: git@github.com:evaleev/libint.git           # [linux]
    #git_url: https://github.com/evaleev/libint.git       # [osx]
    #git_tag: 5c89451  # L5-6: v1, 1.2.1 + 13 = 5c89451, L5: am8, L6M2: hand-edited to incl libderiv/libderiv.h

build:
    number: 4                                            # [linux]  # 4 is to have components and fma # 3 is to get tarball # 2 turns off sph eri3
    number: 1                                            # [osx]    # 1 is build30
    binary_relocation: true
    skip: true                                           # [win]
    run_exports:
        - {{ pin_subpackage('libint2', max_pin='x') }}
    #ignore_run_exports:
    #    # gcc symbols linked statically. c++ only a formality to build c lib.
    #    - libgcc-ng                                      # [linux]
    #    - libstdcxx-ng                                   # [linux]
    #    - libcxx                                         # [osx]

requirements:
    build:
        - cmake >=3.8
        - {{ compiler('cxx') }}
        - ninja
    host:
        - boost
        - eigen
        - mpfr

test:
    commands:
        # Verify library
        - test -f $PREFIX/lib/libint2$SHLIB_EXT
        # Inspect linkage
        - ldd -r -u $PREFIX/lib/libint2.so && return 0 # [linux]
        - ldd -v $PREFIX/lib/libint2.so                # [linux]
        - otool -L $PREFIX/lib/libint2.dylib           # [osx]
        - conda-inspect linkages libint2 --show-files

about:
    home: https://github.com/evaleev/libint
    dev_url: https://github.com/evaleev/libint
    doc_url: http://evaleev.github.io/libint/
    doc_source_url: https://github.com/evaleev/libint/blob/master/doc/progman/progman.tex
    license: LGPL-3.0+
    license_url: https://opensource.org/licenses/LGPL-3.0+
    license_file: LICENSE
    license_family: LGPL
    summary: "E. Valeev and J. Fermann's two-body Gaussian molecular integrals"
    # description: >


# NOTES
# -----

# * tried to build an AM6 for linux build/number: 2 at libint2_1574565922374 but it stopped compiling. could be fixable
