{% set version = "3.2.1" %}

package:
    name: dftd3
    version: {{ version }}

source:
    git_url: git@github.com:loriab/dftd3.git             # [linux]
    git_url: https://github.com/loriab/dftd3.git         # [osx]
    git_tag: 8e5463e

build:
    number: 2                                            # [linux]
    number: 1                                            # [osx]
    binary_relocation: true
    skip: true                                           # [win]
    ignore_run_exports:
        # unused libraries
        - libgcc-ng                                      # [linux]
        - libgfortran-ng                                 # [linux]

requirements:
    build:
        - {{ compiler('fortran') }}
        - cmake >=3.3

test:
    commands:
        # Verify executable
        - test -f $PREFIX/bin/dftd3
        - $PREFIX/bin/dftd3 -h
        - $PREFIX/bin/dftd3 -version
        # Inspect linkage
        - ldd -r -u $PREFIX/bin/dftd3                    # [linux]
        - otool -L $PREFIX/bin/dftd3                     # [osx]
        - conda inspect linkages --show-files --groupby=dependency dftd3
        - conda inspect objects -p $PREFIX $PKG_NAME     # [osx]

about:
    home: http://www.thch.uni-bonn.de/tc/index.php?section=downloads&subsection=DFT-D3&lang=english
    # dev_url:
    doc_url: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/dft-d3/man.pdf
    # doc_source_url:
    license: GPL-1.0+
    # license_url:
    license_file: LICENSE
    license_family: GPL
    summary: "S. Grimme's dispersion correction for DFT, Hartree--Fock, and semi-empirical quantum chemical methods"
    # description: >

## History

# v3.2.1
# * _1 removed static, _2 adds ignore_run_exports, _M1 adds -O0

# v3.2.0
# * fn: dftd3.tgz
# * url: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/dft-d3/dftd3.tgz
# * L8/M8
