{% set name = "libxc" %}
{% set version = "5.2.3" %}
{% set sha256 = "6cd45669d7f92bdcdb6879bea232dac94ad57d025cf2edfd019182ccf6494a75" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://gitlab.com/libxc/libxc/-/archive/{{ version }}/libxc-{{ version }}.tar.bz2
    sha256: {{ sha256 }}

build:
    number: 0                                            # [linux]
    number: 0                                            # [osx]
    binary_relocation: true
    skip: true                                           # [win]
    run_exports:
        - {{ pin_subpackage('libxc', max_pin='x') }}
    ignore_run_exports:
        - libstdcxx-ng                                   # [linux]

requirements:
    build:
        - cmake >=3.0
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}                          # [linux]  # cmake wants compiler
        - perl

test:
    commands:
        # Verify library
        - test -L $PREFIX/lib/libxc$SHLIB_EXT
        # Inspect linkage
        - ldd -v $PREFIX/lib/libxc$SHLIB_EXT             # [linux]
        - ldd -v $PREFIX/bin/xc-info                     # [linux]
        - $PREFIX/bin/xc-info 100                        # [linux]
        - otool -L $PREFIX/lib/libxc$SHLIB_EXT           # [osx]
        - conda inspect linkages --show-files --groupby=dependency libxc
        - conda inspect objects -p $PREFIX $PKG_NAME     # [osx]

about:
    home: http://www.tddft.org/programs/Libxc
    dev_url: https://gitlab.com/libxc/libxc
    doc_url: https://gitlab.com/libxc/libxc/wikis/Manual-4.0
    # doc_source_url:
    license: MPL-2.0
    license_url: https://opensource.org/licenses/MPL-2.0
    license_file: COPYING
    license_family: Other
    summary: "M.A.L. Marques's exchange-correlation functionals for density-functional theory"
    # description: >


## NOTES

# * psi4 v1.2-era fork
#   * -DNAMESPACE_INSTALL_INCLUDEDIR="/libxc" \
#   * {% set version = "4.0.2" %}
#   * git_url: git@github.com:psi4/libxc.git              # [linux]
#   * git_url: https://github.com/psi4/libxc.git          # [osx]
#   * git_tag: libxc4retweaked
#   * number: 1                                            # [linux]  # 1: AVX-512
#   * number: 0                                            # [osx]
#   * test -f $PREFIX/lib/libxc$SHLIB_EXT

#    git_url: https://gitlab.com/libxc/libxc.git
#    git_tag: hotfix5.1.0

#    git_tag: 4.3.4  # L0/M0: 4.3.4, broadens to x
#    git_tag: 4.3.3  # L0/M0: 4.3.3
#    git_tag: 4.3.0  # L1/M1 4.3.0, L2 c-b 3.17
#                    # L0/M0 loriab branch

#   {% set version = "5.1.5" %}
#   {% set sha256 = "60d9ead0f62e40991b6ff043242902090141c437343eb345a981ec8e3fd224d8" %}
